set fenc=utf-8
set fencs=utf-8,usc-bom,euc-jp,gb18030,gbk,gb2312,cp936
set encoding=utf-8
set nocompatible
set confirm
set clipboard=unnamedplus
filetype on
filetype plugin on
filetype indent on
syntax on
set mouse=v
set noerrorbells
set showmatch
set incsearch
set autoindent
set cindent
set tabstop=4
set softtabstop=4
set shiftwidth=4
set nosmarttab
set history=300
set nu
set expandtab
set hlsearch
set ruler
set cursorline
set hls
set title
colorscheme desert
syntax enable
